### ISSUE TITLE
Missing Scripts

### ISSUE THREAD

**Issue by turnersr** [MIDA-group/CoMIR#48]
Hello,

very awesome work! I was trying to reproduce your results and found that the scripts referred in 
"
run RegMI.m
run Evaluation_RegMI.m
"
are missing. Do you know where I could find these two programs? 

Thank you!

**Comment by npielawski** [comment]
Hello,

Thanks for you interest in our work!

My colleague @elisabethwetzer worked on those, I will upload them as soon as I get them.

Best,
Nicolas

**Comment by npielawski** [comment]
Hello,

I uploaded the scripts in https://github.com/MIDA-group/CoMIR/tree/master/scripts/MI_registration

Sorry for the delay, both @elisabethwetzer and I are on parental leave at the moment.

Best,
Nicolas
