### ISSUE TITLE
backbone

### ISSUE THREAD

**Issue by paperID2381** [MIDA-group/CoMIR#49]
Hi, Pielawski! The CoMIR uses dense Unets tiramisu as the backbone. However, its encoder/decoder structure is very
cumbersome. Can other lightweight structures be used as  the backbone for CoMIR? Thanks!

**Comment by npielawski** [comment]
Hello paperID2381! Thanks for your interest!

Just to clarify, the tiramisu is not technically a backbone neural network, but the main architecture with use throughout the paper and our experiments. We felt that it was easier not to deal with those more complex architectures. More details about backbone architectures here: https://www.kaggle.com/general/205141.

We tried very simple homemade architectures in the beginning and it worked, though we got better success with the tiramisu one. There is no fundamental problem in trying other networks, but you will get better results if the networks are built for segmentation (so any fully convolutional neural network, U-Net shaped ones are even better).

Feel free to try and keep us updated about it! :)
