### ISSUE TITLE
How to train dataset?

### ISSUE THREAD

**Issue by Jane-HZ** [MIDA-group/CoMIR#52]
Thanks for your great contribution!
There is a problem: if I want to train my own dataset, what should I do? 
Your kind help will be much appreciated.

**Comment by npielawski** [comment]
Hello!
Thanks for your interest!

I suggest you set up a training and testing datasets containing aligned images, not many are necessary, so manual registration is an option. Then you can take a look at the following notebook: https://github.com/MIDA-group/CoMIR/blob/master/train-biodata.ipynb which contains all you need to train and test your model.

Feel free to ask if you have any issues trying out our method.

**Comment by Jane-HZ** [comment]
Thank you very much for your patient reply!
