### ISSUE TITLE
Missing Script

### ISSUE THREAD

**Issue by chengtianxiu** [MIDA-group/CoMIR#53]
Hello,
Very awesome work! I was trying to reproduce your results and found that the scripts referred in
"
run evaluateSIFT.m
"
are missing. Do you know where I could find this program?

Your help would be greatly appreciated! I look forward to your reply, thank you!

**Comment by elisabethwetzer** [comment]
Hello,
I'm sorry for the late response! Thank you for pointing out the scripts for evaluating the SIFT based registration are missing! Just to clarify, "run evalauteSIFT.m" is also missing, not only the scripts referred to in it, right? 
Best, 
Elisabeth

**Comment by glisses** [comment]
Hello,
Really appreciate your work! The majority of the repo is well-written and organized.

I've encountered the same issue. I think the "evalauteSIFT.m" is missing. When computing the registration with Mutual Information, I found that the script "registration.m" referred to by "RegMI.m" is also absent. 

Would it be possible to provide these missing scripts? Your help would be greatly appreciated.

Best,
Kaiang

**Comment by elisabethwetzer** [comment]
Hi! Thank you for your interest in our method! I added Evaluation_RegSIFT.m in the scripts folder (https://github.com/MIDA-group/CoMIR/blob/master/scripts/Evaluation_RegSIFT.m), let us know if you have any more questions :)

Best,
Elisabeth

**Comment by glisses** [comment]
Thank you for the update! It seems that "Evaluation_RegSIFT.m" depends on another script "Import_SIFTResults.m". Could you please provide this one as well? 

Thanks,
Kaiang

**Comment by elisabethwetzer** [comment]
Sorry about that - it's added now!
